(() => {
  "use strict";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const fmtBytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`;
  const hex=n=>`0x${(Number(n)>>>0).toString(16).toUpperCase().padStart(8,"0")}`;
  const fmtTime=s=>{const total=Math.max(0,Math.round(Number(s)||0)),m=Math.floor(total/60),sec=total%60;return `${m}:${String(sec).padStart(2,"0")}`;};
  let state=null;

  function close(){document.querySelector(".nvp-overlay")?.remove();state=null;}
  function overview(p){const h=p.header;return `<div class="nvp-intro"><div><h3>${esc(state.result.file?.name||"video.tns")}</h3><p>NVP is a streamed MPEG-4 Part 2 video container. It is not a regular TI-Nspire document and is not passed to the XML decoder.</p></div><span>NVP1 · v${h.version}</span></div><div class="nvp-stats"><div><small>Video</small><b>${h.videoWidth}×${h.videoHeight}</b><span>Canvas ${h.canvasWidth}×${h.canvasHeight} · x=${h.videoX}, y=${h.videoY}</span></div><div><small>Frame rate</small><b>${p.fps.toFixed(3)} fps</b><span>${h.frameCount.toLocaleString()} frames · ${fmtTime(p.durationSeconds)}</span></div><div><small>Codec</small><b>${esc(p.codec)}</b><span>No audio</span></div><div><small>Chunks</small><b>${h.chunkCount.toLocaleString()}</b><span>Block ${fmtBytes(h.blockSize)}</span></div><div><small>File size</small><b>${fmtBytes(state.session.originalBytes.length)}</b><span>Index ${hex(h.indexOffset)}</span></div><div><small>Subtitles</small><b>${h.subtitleCount.toLocaleString()}</b><span>Offset ${hex(h.subtitleOffset)}</span></div></div><div class="nvp-note">Browser playback is intentionally not faked here: this file stores an MPEG-4 Part 2 elementary stream in NVP chunks, not an ordinary MP4/WebM file. The container can still be validated and inspected safely.</div>`;}
  function chunks(p){const size=150,max=Math.max(1,Math.ceil(p.chunks.length/size));state.page=Math.min(state.page||0,max-1);const start=state.page*size,rows=p.chunks.slice(start,start+size);return `<div class="nvp-toolbar"><div><h3>Chunks</h3><p>${start+1}–${Math.min(start+size,p.chunks.length)} of ${p.chunks.length}</p></div><div><button data-page="prev" ${state.page===0?"disabled":""}>←</button><span>Page ${state.page+1} / ${max}</span><button data-page="next" ${state.page===max-1?"disabled":""}>→</button></div></div><div class="nvp-table-wrap"><table><thead><tr><th>#</th><th>Offset</th><th>Stored</th><th>Frames</th><th>First frame</th><th>Frame table</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${c.index}</td><td>${hex(c.offset)}</td><td>${fmtBytes(c.packedSize)}</td><td>${c.frameCount}</td><td>${c.firstFrame}</td><td>${hex(c.frameTableOffset)}</td></tr>`).join("")}</tbody></table></div>`;}
  function raw(){const b=state.session.originalBytes,limit=Math.min(b.length,8192),lines=[];for(let o=0;o<limit;o+=16){const c=b.subarray(o,Math.min(o+16,limit)),hs=Array.from(c,x=>x.toString(16).padStart(2,"0")).join(" "),as=Array.from(c,x=>x>=32&&x<=126?String.fromCharCode(x):".").join("");lines.push(`${o.toString(16).padStart(8,"0")}  ${hs.padEnd(47," ")}  ${as}`);}return `<h3>Raw container</h3><pre class="nvp-hex">${esc(lines.join("\n"))}${b.length>limit?`\n… ${b.length-limit} more bytes`:""}</pre>`;}
  function exportPanel(){let status="Valid";try{state.session.validate();}catch(e){status=`Invalid: ${e.message}`;}return `<div class="nvp-intro"><div><h3>Validate & export</h3><p>NVP editing is read-only in this first version. Export produces an identical copy.</p></div><span>${esc(status)}</span></div><div class="nvp-actions"><button data-validate>Validate</button><button class="primary" data-export>Export copy</button></div><div data-status class="nvp-status"></div>`;}
  const panels={overview,chunks,raw,export:exportPanel};
  function render(name=state.panel||"overview"){state.panel=name;const p=state.session.parsed;$(".nvp-nav").innerHTML=[["overview","Overview"],["chunks","Chunks"],["raw","Raw"],["export","Validate & export"]].map(([id,l])=>`<button data-nav="${id}" class="${id===name?"active":""}">${l}</button>`).join("");$(".nvp-content").innerHTML=(panels[name]||overview)(p);bind();}
  function bind(){$$('[data-nav]').forEach(b=>b.onclick=()=>render(b.dataset.nav));$$('[data-page]').forEach(b=>b.onclick=()=>{state.page+=b.dataset.page==="next"?1:-1;render("chunks");});$('[data-validate]')?.addEventListener("click",()=>{const s=$('[data-status]');try{state.session.validate();s.textContent="NVP container is valid.";}catch(e){s.textContent=e.message;}});$('[data-export]')?.addEventListener("click",()=>{const bytes=state.session.exportBytes(),blob=new Blob([bytes],{type:"application/octet-stream"}),a=document.createElement("a"),name=state.result.file?.name||"video.tns";a.href=URL.createObjectURL(blob);a.download=name.replace(/\.tns$/i,"-copy.tns");a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});}
  async function open(result){const adapter=result.adapter||window.TnsContainerRegistry?.getAdapter?.(result.adapterId);if(!adapter?.createSession)throw new Error("NVP adapter session is unavailable.");close();state={result,session:adapter.createSession(result),panel:"overview",page:0};const root=document.createElement("div");root.className="nvp-overlay";root.innerHTML=`<section class="nvp-editor"><header><div><span>STRUCTURED TNS VIDEO</span><h2>NVP Video</h2><small>${esc(result.file?.name||"video.tns")} · ${esc(result.formatLabel||"NVP")}</small></div><button data-close>×</button></header><div class="nvp-workspace"><nav class="nvp-nav"></nav><main class="nvp-content"></main></div></section>`;document.body.appendChild(root);root.querySelector('[data-close]').onclick=close;root.addEventListener("mousedown",e=>{if(e.target===root)close();});render("overview");}
  window.TnsNvpEditor=Object.freeze({open,close});
})();